export const LOAD_FAVORITES_TRUE = "LOAD_FAVORITES_TRUE";
export const LOAD_FAVORITES_FALSE = "LOAD_FAVORITES_FALSE";
export const GET_FAVORITES = "GET_FAVORITES";
export const ADD_FAVORITES = "ADD_FAVORITES";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";
export const TOGGLE = "TOGGLE";
